# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TestAT009 < Formula
  desc "test is simple tool that outputs the test lines of its input"
  homepage "https://github.com/ro-tex/test"
  version "0.0.9"
  license "MIT"

  depends_on "go"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ro-tex/test/releases/download/v0.0.9/test_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d159048304f4a1fc4a9b2893feabed8aa4d8deea46c60e97c7aaf801fe24283d"

      def install
        ENV["GOPATH"] = buildpath

        bin_path = buildpath/"src/github.com/ro-tex/test"
        bin_path.install Dir["*"]
        cd bin_path do
            system "go", "build", "-o", bin/"test", "."
        end
        # ...
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ro-tex/test/releases/download/v0.0.9/test_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "9d6a8efd367190cf5d87e1d5f1d83c8a40c185cc490ffa90b01500222dc7b615"

      def install
        ENV["GOPATH"] = buildpath

        bin_path = buildpath/"src/github.com/ro-tex/test"
        bin_path.install Dir["*"]
        cd bin_path do
            system "go", "build", "-o", bin/"test", "."
        end
        # ...
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ro-tex/test/releases/download/v0.0.9/test_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "7d781777ba3dbd66ad38e832f172e29ec21140591c99404e94fed3c1fc51450d"

      def install
        ENV["GOPATH"] = buildpath

        bin_path = buildpath/"src/github.com/ro-tex/test"
        bin_path.install Dir["*"]
        cd bin_path do
            system "go", "build", "-o", bin/"test", "."
        end
        # ...
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ro-tex/test/releases/download/v0.0.9/test_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "4c2fab49edf499f3c6b123d452b64b5a2fe932d780192075764ee252d0955b35"

      def install
        ENV["GOPATH"] = buildpath

        bin_path = buildpath/"src/github.com/ro-tex/test"
        bin_path.install Dir["*"]
        cd bin_path do
            system "go", "build", "-o", bin/"test", "."
        end
        # ...
      end
    end
  end

  test do
    system "#{bin}/test --help"
    # ...
  end
end
