name: Release

on:
  push:
    branches:
      - main

# This is quite broad. We should narrow it down after reading https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
#permissions: write-all

# TODO Re-enable this: concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    permissions:
      contents: write # see https://stackoverflow.com/a/76645503
      pull-requests: write
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install Dependencies
        run: npm install

      #      - name: Set up Go
      #        uses: actions/setup-go@v4

      - name: Create Release Pull Request
        uses: changesets/action@v1.4.7
        #        publish:
        #          goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
