name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    permissions: # see https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
      contents: write # see https://stackoverflow.com/a/76645503
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        #if: steps.changesets.outputs.hasChangesets == 'false'
        uses: nixbuild/nix-quick-install-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        #if: steps.changesets.outputs.hasChangesets == 'false'
        run: nix build . && cp ./result/bin/test test_linux

      - name: Release
        #if: steps.changesets.outputs.hasChangesets == 'false'
        #        uses: softprops/action-gh-release@v2 # https://github.com/softprops/action-gh-release
        #        with:
        #          token: ${{ secrets.GITHUB_TOKEN }}
        #          files: |
        #            test_linux
        #          prerelease: false
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          #automatic_release_tag: "latest"
          prerelease: false
          title: "Something something darkside..."
          files: |
            test_linux
